version: '3.6'

services:
  cars-db:
    image: mysql:8.0.19
    container_name: cars-db
    environment:
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    restart: unless-stopped
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - cars-db-volume:/var/lib/mysql
    networks:
      - cars-net

  cars-api:
    build:
      context: docker/php
      args:
        TIMEZONE: "Europe/Paris"
    container_name: cars-api
    volumes:
      - ./:/var/www/vhosts/cars-api
    working_dir: /var/www/vhosts/cars-api
    networks:
      cars-net:
        aliases:
          - cars-api

  cars-api-nginx:
    image: nginx:latest
    container_name: cars-api-nginx
    ports:
      - "8000:80"
    depends_on:
      - cars-api
    networks:
      - cars-net
    volumes:
      - ./docker/nginx/conf/www-cars-api:/etc/nginx/conf.d/default.conf
      - ./:/var/www/vhosts/cars-api

volumes: 
  cars-db-volume:
networks:
  cars-net:
